### ISSUE TITLE
How can i install this package in Atom?

### ISSUE THREAD

**Issue by agileago** [ddavison/rest-client#20]
I can't find this package in Atom's Setting. when i search `rest`.i can't find it

**Comment by ddavison** [comment]
unfortunately this package didn't make it to the Atom 1.0 API due to it still using deprecated functionality which is why you probably dont see it.

It's easy to fix, i just hadn't gotten to it yet.  If you'd like to take a stab, i'd be willing to accept pull requests :)  otherwise - i'll eventually get to it.

**Comment by agileago** [comment]
oh, it's unfortunately indeed

**Comment by ddavison** [comment]
@agileago v0.4.0 has [just been released](https://github.com/ddavison/rest-client/releases/tag/v0.4.0).. you should be able to install now!
