### ISSUE TITLE
Show response headers

### ISSUE THREAD

**Issue by fcestrada** [ddavison/rest-client#38]
Hi Daniel,

First of all thanks a lot for your hard work in this plugin, currently I'm using it a lot :v: , but I have some REST WS which includes useful information as header and not in the body, so would be possible to display the response headers too?

Thanks in advance for your attention regarding this request.

Best Regards :wink:

**Comment by ddavison** [comment]
hey @fcestrada !  Thanks for the love, brother!  thanks go to @javaguirre as well. I can't take all the credit ;)

sorry it took a while to respond!  been super busy :)

It makes 100% sense to include response headers as well. Did you want to try your hand at creating a pull request to implement this functionality?  If not, myself or @javaguirre can get to it, because i agree complete that this functionality should be in here.

**Comment by javaguirre** [comment]
Yes! I think that's important, I'll do It. :-)

**Comment by fcestrada** [comment]
@javaguirre Muchísimas gracias Javier, saludos desde México :clap:

**Comment by javaguirre** [comment]
Done! We'll need to add a bit of style, but I think we could do that when we add also json syntax higlighting. I'm gonna publish a minor version of the package.

**Comment by javaguirre** [comment]
Done! If you update rest-client to v1.2.0 you're good to go! :-)

Saludos!

**Comment by fcestrada** [comment]
Updated, thank you very much!!! :clap:

Saludos :wink:
